import {tools} from "./Tools.js";

export let items = {
	air: {
		itemName: "air",
		itemType: "material",
		isBreakable: false,
		isWall: false,
		takesUpSpace: false,
		isPlacable: false,
		drops: 0,
		isPlantable: false,
		effectiveTool: null,
		durability: 0,
		stackSize: 0,
	},
	wood: {
		itemName: "wood",
		itemType: "material",
		isBreakable: true,
		isWall: true,
		takesUpSpace: true,
		isPlacable: true,
		drops: 1,
		isPlantable: false,
		effectiveTool: tools.axe,
		durability: 6,
		stackSize: 5,
	},
	smallStone: {
		itemName: "small-stone",
		itemType: "material",
		isBreakable: true,
		isWall: false,
		takesUpSpace: true,
		isPlacable: true,
		drops: 1,
		isPlantable: false,
		effectiveTool: tools.empty,
		durability: 1,
		stackSize: 100,
	},
	plant: {
		itemName: "plant",
		itemType: "material",
		isBreakable: true,
		isWall: false,
		takesUpSpace: true,
		isPlacable: true,
		drops: 1,
		isPlantable: false,
		effectiveTool: tools.empty,
		durability: 1,
		stackSize: 100,
	},
	seeds: {
		itemName: "seeds",
		itemType: "material",
		isBreakable: true,
		isWall: false,
		takesUpSpace: true,
		isPlacable: false,
		drops: 1,
		isPlantable: true,
		effectiveTool: tools.empty,
		durability: 1,
		stackSize: 100,
	},
	farmland: {
		itemName: "farmland",
		itemType: "material",
		isBreakable: true,
		isWall: false,
		takesUpSpace: true,
		isPlacable: false,
		drops: 0,
		isPlantable: false,
		effectiveTool: tools.empty,
		durability: 2,
		stackSize: 0,
	},
	crops: {
		itemName: "crops",
		itemType: "material",
		isBreakable: true,
		isWall: false,
		takesUpSpace: true,
		isPlacable: false,
		drops: 1,
		isPlantable: false,
		effectiveTool: tools.empty,
		durability: 1,
		stackSize: 100,
	},
	grain: {
		itemName: "grain",
		itemType: "material",
		isBreakable: false,
		isWall: false,
		takesUpSpace: false,
		isPlacable: false,
		drops: 0,
		isPlantable: false,
		effectiveTool: null,
		durablility: 0,
		stackSize: 100,
	},
	barrel: {
		itemName: "barrel",
		itemType: "material",
		isBreakable: true,
		isWall: true,
		takesUpSpace: true,
		isPlacable: true,
		drops: 1,
		isPlantable: false,
		effectiveTool: tools.axe,
		durability: 3,
		stackSize: 100,
	},
};

export function getItemByName(name) {
	for (let item in items) {
		if (items[item].itemName === name) {
			return items[item];
		}
	}
}